### ISSUE TITLE
Error thrown from atom: EPERM: operation not permitted, write

### ISSUE THREAD

**Issue by giraugh** [retroverse/execute-command#1]
Happens only with synchronous execution

**Atom Version**: 1.9.9
**System**: Microsoft Windows 10 Home
**Thrown From**: [execute-command](https://github.com/retroverse/execute-command) package, v0.11.0
### Stack Trace

Uncaught Error: EPERM: operation not permitted, write

```
At fs.js:706

Error: EPERM: operation not permitted, write
    at Error (native)
    at Object.fs.writeSync (fs.js:706:20)
    at SyncWriteStream.write (fs.js:2064:6)
    at execSync (child_process.js:519:20)
    at Object.module.exports.ExecuteCommand.execute (file:///C:/Users/ebrea/.atom/packages/execute-command/lib/index.coffee:56:10)
    at atom-workspace.subscriptions.add.atom.commands.add.execute-command:execute (file:///C:/Users/ebrea/.atom/packages/execute-command/lib/index.coffee:32:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\ebrea\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\ebrea\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\ebrea\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\ebrea\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\ebrea\AppData\Local\atom\app-1.9.9\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\ebrea\AppData\Local\atom\app-1.9.9\resources\app.asar\src\window-event-handler.js:3:61)
```
### Commands

```
  2x -1:41.6.0 execute-command:execute (atom-text-editor.editor.is-focused)
     -0:25.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:23.4.0 execute-command:execute (atom-text-editor.editor.is-focused)
     -0:14.5.0 tree-view:remove (li.file.entry.list-item.status-added.selected)
     -0:11.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:10.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.3.0 execute-command:execute (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "autoflow",
      "wrap-guide",
      "keybinding-resolver"
    ]
  },
  "execute-command": {
    "logErrors": true
  }
}
```
### Installed Packages

``` coffee
# User
coffee-compile, v0.22.0 (active)
color-picker, v2.2.2 (active)
compile-less, v1.0.0 (active)
execute-command, v0.11.0 (active)
language-generic-config, v1.1.0 (active)
language-mochascript, v0.0.1 (active)
language-moonscript, v1.7.1 (active)
less-than-slash, v0.16.0 (active)
minimap, v4.24.7 (active)
pigments, v0.33.1 (active)
tree-ignore, v0.6.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by giraugh** [comment]
Fixed in v1.0.0
